# Generated by Django 4.1.4 on 2024-03-01 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Commerce', 'Commerce'), ('Computer Studies', 'Computer Studies'), ('Divinity', 'Divinity'), ('Economics', 'Economics'), ('Electricity', 'Electricity'), ('Entrepreneurship', 'Entrepreneurship'), ('Fine Art', 'Fine Art'), ('French', 'French'), ('Geography', 'Geography'), ('History', 'History'), ('Home Economics', 'Home Economics'), ('Islamiat', 'Islamiat'), ('Kiswahili', 'Kiswahili'), ('Literature in English', 'Literature in English'), ('Luganda', 'Luganda'), ('Mathematics', 'Mathematics'), ('Metalwork', 'Metalwork'), ('Music', 'Music'), ('Physical Education', 'Physical Education'), ('Physics', 'Physics'), ('Subsidiary ICT', 'Subsidiary ICT'), ('Technical Drawing', 'Technical Drawing'), ('Woodwork', 'Woodwork')], max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
